In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [ ]:
df_init = pd.read_csv("https://raw.githubusercontent.com/bluekitsune-sad/mentalHealthAnalyzer/refs/heads/main/notebook/data/mentalhealth_dataset.csv")

# Planning:

===============================================

- Remove unwanted column:

  - timeStamp

- Handling missing values

  - none

- Removing duplicates

  - none

- Removing outliers

  - none

- Normalization and Scaling the data:

  - Age
  - CGPA
  - SymptomFrequency_Last7Days
  - SleepQuality
  - StudyStressLevel
  - StudyHoursPerWeek
  - AcademicEngagement

- Encoding categorical variables:

  - Gender
  - Course
  - Year

- Feature engineering

  - we are not imputing anything as we don't have missing values

===============================================

In [ ]:
df_init.shape

(1000, 16)

Removing the Timestamp column, as it is irrelevant to the model

In [ ]:
df_init = df_init.drop('Timestamp', axis=1)

In [ ]:
df_init.shape

(1000, 15)

In [ ]:
df_init.dtypes

Gender                         object
Age                             int64
Course                         object
YearOfStudy                    object
CGPA                          float64
Depression                      int64
Anxiety                         int64
PanicAttack                     int64
SpecialistTreatment             int64
SymptomFrequency_Last7Days      int64
HasMentalHealthSupport          int64
SleepQuality                    int64
StudyStressLevel                int64
StudyHoursPerWeek               int64
AcademicEngagement              int64
dtype: object

In [ ]:
df_init.columns

Index(['Gender', 'Age', 'Course', 'YearOfStudy', 'CGPA', 'Depression',
       'Anxiety', 'PanicAttack', 'SpecialistTreatment',
       'SymptomFrequency_Last7Days', 'HasMentalHealthSupport', 'SleepQuality',
       'StudyStressLevel', 'StudyHoursPerWeek', 'AcademicEngagement'],
      dtype='object')

In [ ]:
df_init.values

array([['Female', 24, 'Biotechnology', ..., 5, 8, 2],
       ['Female', 18, 'Biotechnology', ..., 4, 13, 5],
       ['Female', 25, 'Biotechnology', ..., 2, 13, 1],
       ...,
       ['Female', 19, 'Human Sciences ', ..., 4, 3, 1],
       ['Female', 24, 'Human Sciences ', ..., 4, 13, 3],
       ['Female', 20, 'Human Sciences ', ..., 5, 8, 1]], dtype=object)

In [ ]:
df_init.head()

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
0,Female,24,Biotechnology,Year 3,2.38,1,0,0,0,5,0,4,5,8,2
1,Female,18,Biotechnology,Year 3,4.00,0,1,0,0,0,0,4,4,13,5
2,Female,25,Biotechnology,Year 3,3.68,0,0,1,0,3,0,1,2,13,1
3,Female,18,Engineering,Year 4,4.00,0,0,0,0,3,0,5,1,19,2
4,Female,20,Engineering,Year 4,2.00,1,1,0,0,0,0,2,4,3,2

In [ ]:
df_init.tail()

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
995,Female,20,KOE,Year 1,2.31,0,1,0,0,6,0,1,3,7,1
996,Female,23,Engineering,Year 1,3.72,1,0,0,0,3,0,4,1,12,2
997,Female,19,Human Sciences,Year 2,2.00,0,0,1,0,1,0,5,4,3,1
998,Female,24,Human Sciences,Year 2,3.89,1,0,1,0,5,0,5,4,13,3
999,Female,20,Human Sciences,Year 2,2.46,1,0,0,0,0,0,2,5,8,1

In [ ]:
df_init.sample(5)

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
154,Female,23,BIT,Year 1,4.0,1,1,1,0,3,0,3,2,18,3
317,Male,19,Mathemathics,Year 4,4.0,1,0,1,0,5,0,1,5,16,2
424,Female,21,Engine,Year 4,2.0,0,1,0,0,1,0,2,4,1,4
559,Female,20,Nursing,Year 3,2.0,0,0,1,0,7,0,2,1,1,5
690,Female,18,ALA,Year 1,4.0,0,1,0,1,2,1,4,5,16,4

In [ ]:
df_init.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      1000 non-null   object
 1   Age                         1000 non-null   int64
 2   Course                      1000 non-null   object
 3   YearOfStudy                 1000 non-null   object
 4   CGPA                        1000 non-null   float64
 5   Depression                  1000 non-null   int64
 6   Anxiety                     1000 non-null   int64
 7   PanicAttack                 1000 non-null   int64
 8   SpecialistTreatment         1000 non-null   int64
 9   SymptomFrequency_Last7Days  1000 non-null   int64
 10  HasMentalHealthSupport      1000 non-null   int64
 11  SleepQuality                1000 non-null   int64
 12  StudyStressLevel            1000 non-null   int64
 13  StudyHoursPerWeek           1000 non-null   int64
 14  AcademicEngagement          1000 non-null   int64
dtypes: float64(1), int64(11), object(3)
memory usage: 117.3+ KB

In [ ]:
df_init.describe()

,Age,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,21.402000,3.122530,0.483000,0.474000,0.458000,0.067000,3.4980,0.067000,2.983000,3.045000,9.746000,3.055000
std,2.373611,0.810961,0.499961,0.499573,0.498482,0.250147,2.3081,0.250147,1.417999,1.417386,5.651497,1.422673
min,18.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,19.000000,2.250000,0.000000,0.000000,0.000000,0.000000,1.7500,0.000000,2.000000,2.000000,5.000000,2.000000
50%,21.000000,3.250000,0.000000,0.000000,0.000000,0.000000,3.0000,0.000000,3.000000,3.000000,9.000000,3.000000
75%,24.000000,4.000000,1.000000,1.000000,1.000000,0.000000,6.0000,0.000000,4.000000,4.000000,15.000000,4.000000
max,25.000000,4.000000,1.000000,1.000000,1.000000,1.000000,7.0000,1.000000,5.000000,5.000000,19.000000,5.000000

In [ ]:
df_init.isnull().sum()

Gender                        0
Age                           0
Course                        0
YearOfStudy                   0
CGPA                          0
Depression                    0
Anxiety                       0
PanicAttack                   0
SpecialistTreatment           0
SymptomFrequency_Last7Days    0
HasMentalHealthSupport        0
SleepQuality                  0
StudyStressLevel              0
StudyHoursPerWeek             0
AcademicEngagement            0
dtype: int64

In [ ]:
df_init.duplicated().sum()

np.int64(0)

# Checking for outliers in the dataset using the IQR method:

In [ ]:
def detect_outliers_iqr(data):
    outlier_summary = {}
    # for column in data.select_dtypes(include=['float64', 'int64']).columns:
    for column in data.select_dtypes(include=['int64']).columns:
        Q1 = data[column].quantile(0.25)
        Q3 = data[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)][column]
        outlier_summary[column] = len(outliers)

        print(f"Column: {column}")
        print(f"  Lower Bound = {lower_bound}")
        print(f"  Upper Bound = {upper_bound}")
        print(f"  Outliers Found = {len(outliers)}\n")

    return outlier_summary

df_forOutlier = df_init.drop(['Depression', 'Anxiety', 'PanicAttack', 'SpecialistTreatment', 'HasMentalHealthSupport'],axis=1)
outlier_counts = detect_outliers_iqr(df_forOutlier)

Column: Age
  Lower Bound = 11.5
  Upper Bound = 31.5
  Outliers Found = 0

Column: SymptomFrequency_Last7Days
  Lower Bound = -4.625
  Upper Bound = 12.375
  Outliers Found = 0

Column: SleepQuality
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

Column: StudyStressLevel
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

Column: StudyHoursPerWeek
  Lower Bound = -10.0
  Upper Bound = 30.0
  Outliers Found = 0

Column: AcademicEngagement
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

# Generate target column based on conditions:

In [ ]:
df_init['IsCounselingNeeded'] = (
    (df_init['Depression'] == 1) |
    (df_init['Anxiety'] == 1) |
    (df_init['PanicAttack'] == 1) |
    (df_init['SpecialistTreatment'] == 1) |
    (df_init['SymptomFrequency_Last7Days'] >= 3) |
    ((df_init['HasMentalHealthSupport'] == 0) &
     ((df_init['SleepQuality'] <= 2) | (df_init['StudyStressLevel'] >= 3))) |
    (df_init['CGPA'] <= 2.5) |
    (df_init['AcademicEngagement'] <= 2)
).astype(int)

In [ ]:
print(df_init['IsCounselingNeeded'].value_counts(normalize=True))

IsCounselingNeeded
1    0.997
0    0.003
Name: proportion, dtype: float64

In [ ]:
df_init.sample(5)

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement,IsCounselingNeeded
204,Female,21,KOE,Year 3,3.67,1,0,0,0,5,0,3,4,13,2,1
882,Male,19,BCS,Year 2,2.71,1,1,1,0,2,0,2,5,5,2,1
788,Female,21,DIPLOMA TESL,Year 3,3.79,1,1,0,0,5,0,1,4,12,2,1
377,Female,22,BCS,Year 4,2.00,0,1,0,0,6,0,2,4,2,1,1
479,Female,23,KOE,Year 3,2.77,0,1,1,0,3,0,2,3,7,5,1

# Encoding the 'YearOfStudy' as it is the only column where ordinal encoding needed:

In [ ]:
X = df_init.drop('IsCounselingNeeded', axis=1)
y = df_init['IsCounselingNeeded']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

((700, 15), (300, 15))

In [ ]:
categories = [['Year 1', 'Year 2', 'Year 3', 'Year 4']]

oe = OrdinalEncoder(categories=categories)

# Fit only on YearOfStudy
X_train[['YearOfStudy']] = oe.fit_transform(X_train[['YearOfStudy']])
X_test[['YearOfStudy']] = oe.transform(X_test[['YearOfStudy']])

In [ ]:
X_train[['YearOfStudy']]

     YearOfStudy
105          1.0
68           2.0
479          2.0
399          0.0
434          0.0
..           ...
835          0.0
192          0.0
629          0.0
559          2.0
684          3.0

[700 rows x 1 columns]

# Performing one-hot encoding on the 'Gender' and 'Course' columns:

In [ ]:
# for Gender
df_init['Gender'].value_counts()

NameError: name 'df' is not defined

In [ ]:
# for Course
df_encodingGender['Course'].value_counts()

In [ ]:
# Count frequency of each course
course_counts = df['Course'].value_counts()

# Replace courses that occur less than 20 times with "Other"
df['Course'] = df['Course'].apply(lambda x: x if course_counts[x] >= 20 else 'Other')

# Now one-hot encode again
# df_encodingGenderAndCourse = pd.get_dummies(df, columns=['Course'], drop_first=True)
df_encodingGenderAndCourse = pd.get_dummies(df, columns=['Gender','Course'], drop_first=True)

# Convert only the one-hot encoded columns to integer type
for col in df_encodingGenderAndCourse.columns:
    if col.startswith('Course_') or col.startswith('Gender_'):
        df_encodingGenderAndCourse[col] = df_encodingGenderAndCourse[col].astype(int)

print(df_encodingGenderAndCourse.filter(like='Course_').head())
print(df_encodingGenderAndCourse.filter(like='Gender_').head())

In [ ]:
# df_encodingGender = pd.get_dummies(df, columns = ['Gender'], drop_first=True)
# for col in df_encodingGender.columns:
#     if col.startswith('Gender_'):
#         df_encodingGender[col] = df_encodingGender[col].astype(int)

# print("\nFinal columns with Integer Values for One-Hot Encoded Columns:\n", df_encodingGender['Gender_Male'])

In [ ]:
# # Count frequency of each course
# course_counts = df['Course'].value_counts()

# # Replace courses that occur less than 20 times with "Other"
# df['Course'] = df['Course'].apply(lambda x: x if course_counts[x] >= 20 else 'Other')

# # Now one-hot encode again
# # df_encodingGenderAndCourse = pd.get_dummies(df, columns=['Course'], drop_first=True)
# df_encodingGenderAndCourse = pd.get_dummies(df, columns=['Course'])

# # Convert only the one-hot encoded columns to integer type
# for col in df_encodingGenderAndCourse.columns:
#     if col.startswith('Course_'):
#         df_encodingGenderAndCourse[col] = df_encodingGenderAndCourse[col].astype(int)

# print(df_encodingGenderAndCourse.filter(like='Course_').head())

In [ ]:
df_encodingGenderAndCourse.shape

# Normalization and Scaling the data:

  - Age
  - CGPA
  - SymptomFrequency_Last7Days
  - SleepQuality
  - StudyStressLevel
  - StudyHoursPerWeek
  - AcademicEngagement

In [ ]:
X = df_encodingGenderAndCourse.drop('IsCounselingNeeded', axis=1)
y = df_encodingGenderAndCourse['IsCounselingNeeded']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

In [ ]:
scaler = StandardScaler()

cols_to_scale = [
    'Age',
    'CGPA',
    'SymptomFrequency_Last7Days',
    'SleepQuality',
    'StudyStressLevel',
    'StudyHoursPerWeek',
    'AcademicEngagement'
]

# Fit only on training set
X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])

# Transform test set with same scaler
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

scaler = MinMaxScaler()

X_train[cols_to_scale] = scaler.fit_transform(X_train[cols_to_scale])
X_test[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

In [ ]:
X_train.sample(5)

In [ ]:
df_encodingGenderAndCourse.columns

In [ ]:
must see how to merge yearofstyudy and the scaled and normalized columns

In [ ]:
# df.corr()