In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [27]:
df_init = pd.read_csv("https://raw.githubusercontent.com/bluekitsune-sad/mentalHealthAnalyzer/refs/heads/main/dataset/mentalhealth_dataset.csv")

===============================================

- Remove unwanted column:

  - timeStamp

- Handling missing values

  - none

- Removing duplicates

  - none

- Removing outliers

  - none

- Normalization and Scaling the data:

  - Age
  - CGPA
  - SymptomFrequency_Last7Days
  - SleepQuality
  - StudyStressLevel
  - StudyHoursPerWeek
  - AcademicEngagement

- Encoding categorical variables:

  - Gender
  - Course
  - Year

- Feature engineering

===============================================

In [28]:
df.shape

(1000, 15)

Removing the Timestamp column, as it is irrelevant to the model

In [29]:
df = df_init.drop('Timestamp', axis=1)

In [30]:
df.shape

(1000, 15)

In [31]:
df.dtypes

Gender                         object
Age                             int64
Course                         object
YearOfStudy                    object
CGPA                          float64
Depression                      int64
Anxiety                         int64
PanicAttack                     int64
SpecialistTreatment             int64
SymptomFrequency_Last7Days      int64
HasMentalHealthSupport          int64
SleepQuality                    int64
StudyStressLevel                int64
StudyHoursPerWeek               int64
AcademicEngagement              int64
dtype: object

In [32]:
df.columns

Index(['Gender', 'Age', 'Course', 'YearOfStudy', 'CGPA', 'Depression',
       'Anxiety', 'PanicAttack', 'SpecialistTreatment',
       'SymptomFrequency_Last7Days', 'HasMentalHealthSupport', 'SleepQuality',
       'StudyStressLevel', 'StudyHoursPerWeek', 'AcademicEngagement'],
      dtype='object')

In [33]:
df.values

array([['Female', 24, 'Biotechnology', ..., 5, 8, 2],
       ['Female', 18, 'Biotechnology', ..., 4, 13, 5],
       ['Female', 25, 'Biotechnology', ..., 2, 13, 1],
       ...,
       ['Female', 19, 'Human Sciences ', ..., 4, 3, 1],
       ['Female', 24, 'Human Sciences ', ..., 4, 13, 3],
       ['Female', 20, 'Human Sciences ', ..., 5, 8, 1]], dtype=object)

In [34]:
df.head()

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
0,Female,24,Biotechnology,Year 3,2.38,1,0,0,0,5,0,4,5,8,2
1,Female,18,Biotechnology,Year 3,4.00,0,1,0,0,0,0,4,4,13,5
2,Female,25,Biotechnology,Year 3,3.68,0,0,1,0,3,0,1,2,13,1
3,Female,18,Engineering,year 4,4.00,0,0,0,0,3,0,5,1,19,2
4,Female,20,Engineering,year 4,2.00,1,1,0,0,0,0,2,4,3,2

In [35]:
df.tail()

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
995,Female,20,KOE,year 1,2.31,0,1,0,0,6,0,1,3,7,1
996,Female,23,Engineering,year 1,3.72,1,0,0,0,3,0,4,1,12,2
997,Female,19,Human Sciences,Year 2,2.00,0,0,1,0,1,0,5,4,3,1
998,Female,24,Human Sciences,Year 2,3.89,1,0,1,0,5,0,5,4,13,3
999,Female,20,Human Sciences,Year 2,2.46,1,0,0,0,0,0,2,5,8,1

In [36]:
df.sample(5)

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
96,Male,25,Engineering,year 1,2.28,0,1,0,0,4,0,4,2,5,4
609,Female,18,BIT,Year 2,2.99,1,1,1,0,6,0,1,2,6,2
958,Female,25,Benl,year 1,3.82,0,1,1,0,5,0,1,5,10,5
928,Female,24,BCS,year 2,2.00,1,1,0,0,3,0,3,3,1,3
910,Male,21,BIT,year 1,3.94,0,0,0,0,7,0,4,3,14,4

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      1000 non-null   object
 1   Age                         1000 non-null   int64
 2   Course                      1000 non-null   object
 3   YearOfStudy                 1000 non-null   object
 4   CGPA                        1000 non-null   float64
 5   Depression                  1000 non-null   int64
 6   Anxiety                     1000 non-null   int64
 7   PanicAttack                 1000 non-null   int64
 8   SpecialistTreatment         1000 non-null   int64
 9   SymptomFrequency_Last7Days  1000 non-null   int64
 10  HasMentalHealthSupport      1000 non-null   int64
 11  SleepQuality                1000 non-null   int64
 12  StudyStressLevel            1000 non-null   int64
 13  StudyHoursPerWeek           1000 non-null   int64
 14  AcademicEngagement          1000 non-null   int64
dtypes: float64(1), int64(11), object(3)
memory usage: 117.3+ KB

In [38]:
df.describe()

,Age,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,21.402000,3.122530,0.483000,0.474000,0.458000,0.067000,3.4980,0.067000,2.983000,3.045000,9.746000,3.055000
std,2.373611,0.810961,0.499961,0.499573,0.498482,0.250147,2.3081,0.250147,1.417999,1.417386,5.651497,1.422673
min,18.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,19.000000,2.250000,0.000000,0.000000,0.000000,0.000000,1.7500,0.000000,2.000000,2.000000,5.000000,2.000000
50%,21.000000,3.250000,0.000000,0.000000,0.000000,0.000000,3.0000,0.000000,3.000000,3.000000,9.000000,3.000000
75%,24.000000,4.000000,1.000000,1.000000,1.000000,0.000000,6.0000,0.000000,4.000000,4.000000,15.000000,4.000000
max,25.000000,4.000000,1.000000,1.000000,1.000000,1.000000,7.0000,1.000000,5.000000,5.000000,19.000000,5.000000

In [39]:
df.isnull().sum()

Gender                        0
Age                           0
Course                        0
YearOfStudy                   0
CGPA                          0
Depression                    0
Anxiety                       0
PanicAttack                   0
SpecialistTreatment           0
SymptomFrequency_Last7Days    0
HasMentalHealthSupport        0
SleepQuality                  0
StudyStressLevel              0
StudyHoursPerWeek             0
AcademicEngagement            0
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)

Checking for outliers in the dataset using the IQR method.

In [47]:
def detect_outliers_iqr(data):
    outlier_summary = {}
    # for column in data.select_dtypes(include=['float64', 'int64']).columns:
    for column in data.select_dtypes(include=['int64']).columns:
        Q1 = data[column].quantile(0.25)
        Q3 = data[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)][column]
        outlier_summary[column] = len(outliers)

        print(f"Column: {column}")
        print(f"  Lower Bound = {lower_bound}")
        print(f"  Upper Bound = {upper_bound}")
        print(f"  Outliers Found = {len(outliers)}\n")

    return outlier_summary

df_forOutlier = df.drop(['Depression', 'Anxiety', 'PanicAttack', 'SpecialistTreatment', 'HasMentalHealthSupport'],axis=1)
outlier_counts = detect_outliers_iqr(df_forOutlier)

Column: Age
  Lower Bound = 13.0
  Upper Bound = 29.0
  Outliers Found = 0

Column: SymptomFrequency_Last7Days
  Lower Bound = -6.5
  Upper Bound = 13.5
  Outliers Found = 0

Column: SleepQuality
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

Column: StudyStressLevel
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

Column: StudyHoursPerWeek
  Lower Bound = -10.0
  Upper Bound = 30.0
  Outliers Found = 0

Column: AcademicEngagement
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

In [40]:
X = df.drop('purchased', axis=1)
y = df['purchased']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

In [42]:
# df.corr()