In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [53]:
df_init = pd.read_csv("https://raw.githubusercontent.com/bluekitsune-sad/mentalHealthAnalyzer/refs/heads/main/dataset/mentalhealth_dataset.csv")

# Planning:

===============================================

- Remove unwanted column:

  - timeStamp

- Handling missing values

  - none

- Removing duplicates

  - none

- Removing outliers

  - none

- Normalization and Scaling the data:

  - Age
  - CGPA
  - SymptomFrequency_Last7Days
  - SleepQuality
  - StudyStressLevel
  - StudyHoursPerWeek
  - AcademicEngagement

- Encoding categorical variables:

  - Gender
  - Course
  - Year

- Feature engineering

===============================================

In [54]:
df.shape

(933, 16)

Removing the Timestamp column, as it is irrelevant to the model

In [55]:
df = df_init.drop('Timestamp', axis=1)

In [56]:
df.shape

(1000, 15)

In [57]:
df.dtypes

Gender                         object
Age                             int64
Course                         object
YearOfStudy                    object
CGPA                          float64
Depression                      int64
Anxiety                         int64
PanicAttack                     int64
SpecialistTreatment             int64
SymptomFrequency_Last7Days      int64
HasMentalHealthSupport          int64
SleepQuality                    int64
StudyStressLevel                int64
StudyHoursPerWeek               int64
AcademicEngagement              int64
dtype: object

In [58]:
df.columns

Index(['Gender', 'Age', 'Course', 'YearOfStudy', 'CGPA', 'Depression',
       'Anxiety', 'PanicAttack', 'SpecialistTreatment',
       'SymptomFrequency_Last7Days', 'HasMentalHealthSupport', 'SleepQuality',
       'StudyStressLevel', 'StudyHoursPerWeek', 'AcademicEngagement'],
      dtype='object')

In [59]:
df.values

array([['Female', 24, 'Biotechnology', ..., 5, 8, 2],
       ['Female', 18, 'Biotechnology', ..., 4, 13, 5],
       ['Female', 25, 'Biotechnology', ..., 2, 13, 1],
       ...,
       ['Female', 19, 'Human Sciences ', ..., 4, 3, 1],
       ['Female', 24, 'Human Sciences ', ..., 4, 13, 3],
       ['Female', 20, 'Human Sciences ', ..., 5, 8, 1]], dtype=object)

In [60]:
df.head()

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
0,Female,24,Biotechnology,Year 3,2.38,1,0,0,0,5,0,4,5,8,2
1,Female,18,Biotechnology,Year 3,4.00,0,1,0,0,0,0,4,4,13,5
2,Female,25,Biotechnology,Year 3,3.68,0,0,1,0,3,0,1,2,13,1
3,Female,18,Engineering,Year 4,4.00,0,0,0,0,3,0,5,1,19,2
4,Female,20,Engineering,Year 4,2.00,1,1,0,0,0,0,2,4,3,2

In [61]:
df.tail()

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
995,Female,20,KOE,Year 1,2.31,0,1,0,0,6,0,1,3,7,1
996,Female,23,Engineering,Year 1,3.72,1,0,0,0,3,0,4,1,12,2
997,Female,19,Human Sciences,Year 2,2.00,0,0,1,0,1,0,5,4,3,1
998,Female,24,Human Sciences,Year 2,3.89,1,0,1,0,5,0,5,4,13,3
999,Female,20,Human Sciences,Year 2,2.46,1,0,0,0,0,0,2,5,8,1

In [62]:
df.sample(5)

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
314,Female,25,Laws,Year 3,2.83,1,1,1,0,7,0,3,3,5,4
535,Male,19,Engineering,Year 2,2.78,1,1,0,0,2,0,4,2,8,2
34,Female,20,KOE,Year 2,4.00,0,0,0,0,6,0,3,3,19,2
856,Female,22,KOE,Year 2,4.00,1,1,1,0,2,0,4,5,17,3
887,Female,22,BIT,Year 1,4.00,1,1,0,0,6,0,5,4,19,5

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Gender                      1000 non-null   object
 1   Age                         1000 non-null   int64
 2   Course                      1000 non-null   object
 3   YearOfStudy                 1000 non-null   object
 4   CGPA                        1000 non-null   float64
 5   Depression                  1000 non-null   int64
 6   Anxiety                     1000 non-null   int64
 7   PanicAttack                 1000 non-null   int64
 8   SpecialistTreatment         1000 non-null   int64
 9   SymptomFrequency_Last7Days  1000 non-null   int64
 10  HasMentalHealthSupport      1000 non-null   int64
 11  SleepQuality                1000 non-null   int64
 12  StudyStressLevel            1000 non-null   int64
 13  StudyHoursPerWeek           1000 non-null   int64
 14  AcademicEngagement          1000 non-null   int64
dtypes: float64(1), int64(11), object(3)
memory usage: 117.3+ KB

In [64]:
df.describe()

,Age,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,21.402000,3.122530,0.483000,0.474000,0.458000,0.067000,3.4980,0.067000,2.983000,3.045000,9.746000,3.055000
std,2.373611,0.810961,0.499961,0.499573,0.498482,0.250147,2.3081,0.250147,1.417999,1.417386,5.651497,1.422673
min,18.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,19.000000,2.250000,0.000000,0.000000,0.000000,0.000000,1.7500,0.000000,2.000000,2.000000,5.000000,2.000000
50%,21.000000,3.250000,0.000000,0.000000,0.000000,0.000000,3.0000,0.000000,3.000000,3.000000,9.000000,3.000000
75%,24.000000,4.000000,1.000000,1.000000,1.000000,0.000000,6.0000,0.000000,4.000000,4.000000,15.000000,4.000000
max,25.000000,4.000000,1.000000,1.000000,1.000000,1.000000,7.0000,1.000000,5.000000,5.000000,19.000000,5.000000

In [65]:
df.isnull().sum()

Gender                        0
Age                           0
Course                        0
YearOfStudy                   0
CGPA                          0
Depression                    0
Anxiety                       0
PanicAttack                   0
SpecialistTreatment           0
SymptomFrequency_Last7Days    0
HasMentalHealthSupport        0
SleepQuality                  0
StudyStressLevel              0
StudyHoursPerWeek             0
AcademicEngagement            0
dtype: int64

In [66]:
df.duplicated().sum()

np.int64(0)

# Checking for outliers in the dataset using the IQR method:

In [67]:
def detect_outliers_iqr(data):
    outlier_summary = {}
    # for column in data.select_dtypes(include=['float64', 'int64']).columns:
    for column in data.select_dtypes(include=['int64']).columns:
        Q1 = data[column].quantile(0.25)
        Q3 = data[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        outliers = data[(data[column] < lower_bound) | (data[column] > upper_bound)][column]
        outlier_summary[column] = len(outliers)

        print(f"Column: {column}")
        print(f"  Lower Bound = {lower_bound}")
        print(f"  Upper Bound = {upper_bound}")
        print(f"  Outliers Found = {len(outliers)}\n")

    return outlier_summary

df_forOutlier = df.drop(['Depression', 'Anxiety', 'PanicAttack', 'SpecialistTreatment', 'HasMentalHealthSupport'],axis=1)
outlier_counts = detect_outliers_iqr(df_forOutlier)

Column: Age
  Lower Bound = 11.5
  Upper Bound = 31.5
  Outliers Found = 0

Column: SymptomFrequency_Last7Days
  Lower Bound = -4.625
  Upper Bound = 12.375
  Outliers Found = 0

Column: SleepQuality
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

Column: StudyStressLevel
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

Column: StudyHoursPerWeek
  Lower Bound = -10.0
  Upper Bound = 30.0
  Outliers Found = 0

Column: AcademicEngagement
  Lower Bound = -1.0
  Upper Bound = 7.0
  Outliers Found = 0

# Generate target column based on conditions:

In [68]:
df['IsCounselingNeeded'] = (
    (df['Depression'] == 1) |
    (df['Anxiety'] == 1) |
    (df['PanicAttack'] == 1) |
    (df['SpecialistTreatment'] == 1) |
    (df['SymptomFrequency_Last7Days'] >= 3) |
    ((df['HasMentalHealthSupport'] == 0) &
     ((df['SleepQuality'] <= 2) | (df['StudyStressLevel'] >= 3))) |
    (df['CGPA'] <= 2.5) |
    (df['AcademicEngagement'] <= 2)
).astype(int)

In [69]:
df.sample(5)

,Gender,Age,Course,YearOfStudy,CGPA,Depression,Anxiety,PanicAttack,SpecialistTreatment,SymptomFrequency_Last7Days,HasMentalHealthSupport,SleepQuality,StudyStressLevel,StudyHoursPerWeek,AcademicEngagement,IsCounselingNeeded
178,Female,19,BIT,Year 3,2.00,1,0,1,0,1,0,5,4,1,3,1
861,Female,23,Engineering,Year 1,3.10,1,0,1,0,0,0,5,1,9,1,1
96,Male,25,Engineering,Year 1,2.28,0,1,0,0,4,0,4,2,5,4,1
796,Female,23,KOE,Year 2,4.00,0,0,0,0,4,0,1,2,16,5,1
621,Female,24,KOE,Year 2,2.00,0,1,0,0,4,0,1,1,1,2,1

# Encoding the 'YearOfStudy' as it is the only column where ordinal encoding needed:

In [70]:
X = df.drop('IsCounselingNeeded', axis=1)
y = df['IsCounselingNeeded']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
X_train.shape, X_test.shape

((700, 15), (300, 15))

In [74]:
categories = [['Year 1', 'Year 2', 'Year 3', 'Year 4']]

oe = OrdinalEncoder(categories=categories)

# Fit only on YearOfStudy
X_train[['YearOfStudy']] = oe.fit_transform(X_train[['YearOfStudy']])
X_test[['YearOfStudy']] = oe.transform(X_test[['YearOfStudy']])

In [76]:
X_train[['YearOfStudy']]

     YearOfStudy
105          1.0
68           2.0
479          2.0
399          0.0
434          0.0
..           ...
835          0.0
192          0.0
629          0.0
559          2.0
684          3.0

[700 rows x 1 columns]

# Performing one-hot encoding on the 'Gender' and 'Course' columns:

In [78]:
# for Gender
df['Gender'].value_counts()

Gender
Female    760
Male      240
Name: count, dtype: int64

In [88]:
one_hot_encoded_data = pd.get_dummies(df, columns = ['Gender'], drop_first=True)

In [92]:
# Convert only the one-hot encoded columns to integer type
for col in one_hot_encoded_data.columns:
    if col.startswith('Gender_'):
        one_hot_encoded_data[col] = one_hot_encoded_data[col].astype(int)

print("\nFinal columns with Integer Values for One-Hot Encoded Columns:\n", one_hot_encoded_data['Gender_Male'])

Final columns with Integer Values for One-Hot Encoded Columns:
 0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: Gender_Male, Length: 1000, dtype: int64

In [98]:
# for Course
df['Course'].value_counts()

Course
Engineering                180
BCS                        177
BIT                        101
KOE                         39
Biomedical science          33
Laws                        19
Engine                      19
psychology                  17
BENL                        16
CTS                         15
Koe                         14
engin                       14
Business Administration     14
Law                         13
Human Sciences              13
Nursing                     13
Communication               13
Marine science              12
Psychology                  12
Kirkhs                      12
Malcom                      12
Pendidikan Islam            12
Accounting                  11
Fiqh                        11
DIPLOMA TESL                11
Usuluddin                   11
KIRKHS                      10
Pendidikan islam            10
Irkhs                       10
Radiography                  9
TAASL                        9
Human Resources              9
Fiqh fatwa                   9
Mathemathics                 9
ENM                          9
Islamic education            9
Biotechnology                8
IT                           8
Diploma Nursing              8
Kop                          8
koe                          8
Econs                        8
Benl                         8
KENMS                        7
Pendidikan Islam             7
MHSC                         6
Banking Studies              6
ALA                          6
Islamic Education            5
Name: count, dtype: int64

In [100]:
# Count frequency of each course
course_counts = df['Course'].value_counts()

# Replace courses that occur less than 20 times with "Other"
df['Course'] = df['Course'].apply(lambda x: x if course_counts[x] >= 20 else 'Other')

# Now one-hot encode again
# one_hot_encoded_data = pd.get_dummies(df, columns=['Course'], drop_first=True)
one_hot_encoded_data = pd.get_dummies(df, columns=['Course'])

# Convert only the one-hot encoded columns to integer type
for col in one_hot_encoded_data.columns:
    if col.startswith('Course_'):
        one_hot_encoded_data[col] = one_hot_encoded_data[col].astype(int)

print(one_hot_encoded_data.filter(like='Course_').head())

   Course_BCS  Course_BIT  Course_Biomedical science  Course_Engineering  \
0           0           0                          0                   0
1           0           0                          0                   0
2           0           0                          0                   0
3           0           0                          0                   1
4           0           0                          0                   1

   Course_KOE  Course_Other
0           0             1
1           0             1
2           0             1
3           0             0
4           0             0

In [79]:
# df.corr()